services:

  ingestion:
    build: ./services/ingestion
    container_name: ingestion
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data:ro
    networks:
      - pipeline

  preprocessing:
    build: ./services/preprocessing
    container_name: preprocessing
    ports:
      - "8002:8002"
    networks:
      - pipeline

  feature_selection:
    build: ./services/feature_selection
    container_name: feature_selection
    ports:
      - "8003:8003"
    networks:
      - pipeline

  training:
    build: ./services/training
    container_name: training
    ports:
      - "8004:8004"
    networks:
      - pipeline

  prediction:
    build: ./services/prediction
    container_name: prediction
    ports:
      - "8005:8005"
    networks:
      - pipeline

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
    networks:
      - pipeline
    depends_on:
      - ingestion
      - preprocessing
      - feature_selection
      - training
      - prediction

networks:
  pipeline:
    driver: bridge